### PR TITLE
fix: max increase in base fee is 12.5%

### PR DESCRIPTION
**Pull request by poolpitako**

### CODE REVIEW

**Comment by ptrwtts** [comment]
Can you give some context for this change? Thanks!

**Comment by poolpitako** [comment]
> Can you give some context for this change? Thanks!

From https://ethereum.org/en/developers/docs/gas/:

```
The base fee is calculated by a formula that compares the size of the previous block (the amount of gas used for all the transactions) with the target size. The base fee will increase by a maximum of 12.5% per block if the target block size is exceeded. This exponential growth makes it economically non-viable for block size to remain high indefinitely.
```

**Comment by ptrwtts** [comment]
Gotcha. Since base fee will increase by at most 12.5%, no need to have a 30% buffer.

**Comment by georgeroman** [comment]
The reason we give a 30% buffer instead of a 12.5% one is to avoid situations where the transaction(s) don't get included in currentBlock + 1, but sometime after. If that's the case then the base fee of the inclusion block can be greater than what we initially assumed. A 30% buffer instead of 12.5% leaves room for a few more blocks.

**Pull request closed without merging**
